# Create the QC Portal Desktop + Start Menu shortcut. Called at the end of the
# root install.ps1 / install.bat; safe to run again on its own.
#
# This is the ONLY thing the shortcut adds over the `qc-portal` command those
# installers already put on the PATH: a way to start the portal without opening a
# terminal. It does not clone, build, or install anything - keep it that way, or
# there are two implementations of the install and they will drift.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File shortcut.ps1 [-InstallDir <path>]
# ASCII ONLY, deliberately. PowerShell 5.1 (what Windows 10 ships) reads a .ps1 with no
# byte-order mark as ANSI, so a UTF-8 em dash decodes to the three characters `a-hat, euro,
# right-curly-quote` -- and 5.1 treats a curly quote as a STRING DELIMITER. One em dash in a
# comment therefore ends a string early and the whole file fails to parse. Keep every
# character in this file plain ASCII.

param(
  [string]$InstallDir = (Join-Path $env:USERPROFILE '.qc-portal')
)

$ErrorActionPreference = 'Stop'

$entry = Join-Path $InstallDir 'bin\qc-portal.mjs'
$icon  = Join-Path $InstallDir 'installer\icons\qc-portal.ico'
if (-not (Test-Path $entry)) { Write-Host "  no install at $InstallDir - skipping shortcut."; exit 0 }

$node = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $node) { $node = Join-Path $env:ProgramFiles 'nodejs\node.exe' }
if (-not (Test-Path $node)) { Write-Host '  node.exe not found - skipping shortcut.'; exit 0 }

# --app is what makes this feel like a desktop app: the launcher starts the server and
# then shows it in a chromeless Chromium window (no tabs, no address bar) rather than a
# browser tab. See openAppWindow() in bin/qc-portal.mjs.
#
# It goes through wscript because the launcher spawns the server detached and exits, so a
# shortcut pointing straight at node would flash a console window on every start. This
# one-line vbs starts it with no window at all.
$vbs = Join-Path $InstallDir 'installer\windows\launch.vbs'
@"
' Generated by installer\windows\shortcut.ps1 - starts the portal with no console window.
CreateObject("WScript.Shell").Run """$node"" ""$entry"" --app", 0, False
"@ | Set-Content -Path $vbs -Encoding ASCII

$shell = New-Object -ComObject WScript.Shell
foreach ($dir in @([Environment]::GetFolderPath('Desktop'),
                   (Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs'))) {
  if (-not (Test-Path $dir)) { continue }
  $lnk = $shell.CreateShortcut((Join-Path $dir 'QC Portal.lnk'))
  $lnk.TargetPath       = "$env:SystemRoot\System32\wscript.exe"
  $lnk.Arguments        = """$vbs"""
  $lnk.WorkingDirectory = $InstallDir
  $lnk.Description      = 'QC Portal - acceptance testing'
  if (Test-Path $icon) { $lnk.IconLocation = $icon }
  $lnk.Save()
  Write-Host "  shortcut: $(Join-Path $dir 'QC Portal.lnk')"
}
