#!/usr/bin/env bash
# Build installer/macos/dist/QC-Portal-Installer.dmg - the macOS equivalent of the
# .exe: one file to hand over, open, and double-click.
#
#   bash installer/macos/build-dmg.sh                 # unsigned (the default)
#   QC_SIGN_ID="Developer ID Application: ..." \
#   QC_NOTARY_PROFILE=qcportal \
#   bash installer/macos/build-dmg.sh                 # signed + notarised
#
# THE GATEKEEPER PROBLEM, measured rather than assumed (macOS 26.4):
#
#   dmg with NO com.apple.quarantine  -> double-click RUNS
#   dmg quarantined, flags 0001       -> double-click BLOCKED ("Apple could not
#                                        verify ... is free of malware")
#   after the user approves it once   -> runs
#
# Only the DOWNLOADER sets quarantine - a browser or Mail. A file that arrives on a
# USB stick, over a network share, or through a sync client is not quarantined, and
# then this image double-clicks with no dialog at all. That is also exactly why the
# `~/Applications/QC Portal.app` the installer writes is never blocked: it is created
# locally, not downloaded.
#
# And note what does NOT help: the block is NOT spctl's assessment. It was reproduced
# on a machine with `spctl --status: assessments disabled`, so `spctl --master-disable`
# is not a workaround. Ad-hoc signing is not one either - it satisfies no notarisation
# check.
#
# So there are exactly two ways to make a DOWNLOADED image double-click:
#
#   1. Notarise it. Needs a paid Apple Developer ID; this script does the whole thing
#      when QC_SIGN_ID and QC_NOTARY_PROFILE are set (see below).
#   2. Don't deliver it through a browser. Put it on a share or a USB stick.
#
# WHY THE PAYLOAD IS AN .app AND NOT A .command: a bare shell script can never be
# notarised - there is nothing to sign. An .app bundle whose executable is a shell
# script CAN be, which is what makes route 1 possible at all. Unsigned, an .app also
# gets the *System Settings -> Privacy & Security -> Open Anyway* button, which Apple
# documents for applications (not verified here - it needs a real GUI).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
DIST="$HERE/dist"
STAGE="$(mktemp -d)"
VOL='QC Portal Installer'
DMG="$DIST/QC-Portal-Installer.dmg"
APP="$STAGE/Install QC Portal.app"
RAW='https://raw.githubusercontent.com/haonguyenstech/qc-portal/main/install.sh'
SIGN_ID="${QC_SIGN_ID:-}"
NOTARY_PROFILE="${QC_NOTARY_PROFILE:-}"

trap 'rm -rf "$STAGE"' EXIT
mkdir -p "$DIST"

# ---------------------------------------------------------------- the installer app
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Install QC Portal</string>
  <key>CFBundleDisplayName</key><string>Install QC Portal</string>
  <key>CFBundleIdentifier</key><string>com.stsdata.qcportal.installer</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleExecutable</key><string>install-qc-portal</string>
  <key>CFBundleIconFile</key><string>qc-portal</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <!-- No window of its own: it hands the work to Terminal and exits. -->
  <key>LSUIElement</key><true/>
</dict>
</plist>
PLIST
[ -f "$ROOT/installer/icons/qc-portal.icns" ] && cp "$ROOT/installer/icons/qc-portal.icns" "$APP/Contents/Resources/qc-portal.icns"

# The executable hands the install to Terminal and exits. It deliberately runs the
# project's own install.sh FETCHED FRESH rather than a copy carried in the image, for
# two reasons: an image left on a share for six months cannot install a stale
# installer, and there is no second script inside the bundle for Gatekeeper to assess.
cat > "$APP/Contents/MacOS/install-qc-portal" <<LAUNCH
#!/bin/bash
# Generated by installer/macos/build-dmg.sh. Opens Terminal and runs the installer
# there, because the install takes minutes and prints what it is doing -- a progress
# bar we would have to invent, badly.
set -eu
osascript <<'OSA'
tell application "Terminal"
  activate
  do script "clear; echo 'QC Portal installer'; echo; curl -fsSL $RAW | bash"
end tell
OSA
LAUNCH
chmod +x "$APP/Contents/MacOS/install-qc-portal"

# ------------------------------------------------------------------ the README
cat > "$STAGE/READ ME FIRST.txt" <<TXT
QC Portal - install
===================

Double-click "Install QC Portal". A Terminal window opens and does the work: it
installs Node, Git and Claude Code if they are missing, downloads the portal and
builds it. A few minutes. Leave it alone until it says Done.

Afterwards you get a "QC Portal" app in Launchpad - click it and the portal opens
in its own window - plus a \`qc-portal\` command in a new terminal (--stop,
--status, --update). One thing stays yours to do: sign in to Claude once, either
by running \`claude\` or with Auto Agent AI > Connect in the portal's sidebar.


IF macOS SAYS IT "COULD NOT VERIFY" THE APP
-------------------------------------------

That appears when this image was downloaded with a WEB BROWSER, and it means the
installer is not signed by Apple - not that anything is wrong with it. Press Done,
then either:

  * System Settings > Privacy & Security, scroll to Security, and click
    "Open Anyway" next to "Install QC Portal was blocked". Then double-click again.

  * Or skip the image entirely and paste this one line into Terminal:

        curl -fsSL $RAW | bash

    It does exactly the same thing.

You will not see that warning at all if you got this image on a USB stick, from a
shared folder, or through a sync client such as Google Drive - macOS only marks
browser and Mail downloads.

Requires an internet connection.
TXT

[ -f "$ROOT/installer/icons/qc-portal.icns" ] && cp "$ROOT/installer/icons/qc-portal.icns" "$STAGE/.VolumeIcon.icns"

# ------------------------------------------------------------- sign, if we can
if [ -n "$SIGN_ID" ]; then
  echo "signing the app as: $SIGN_ID"
  # --options runtime (the hardened runtime) is REQUIRED for notarisation; without it
  # notarytool accepts the upload and then fails the ticket.
  codesign --force --timestamp --options runtime --sign "$SIGN_ID" "$APP"
  codesign --verify --strict --verbose=2 "$APP"
else
  echo "unsigned (set QC_SIGN_ID to sign; see the comment at the top of this file)"
fi

# ------------------------------------------------------------------- the image
rm -f "$DMG"
hdiutil create -quiet -volname "$VOL" -srcfolder "$STAGE" -ov -format UDZO "$DMG"

if [ -n "$SIGN_ID" ]; then
  codesign --force --timestamp --sign "$SIGN_ID" "$DMG"
  if [ -n "$NOTARY_PROFILE" ]; then
    echo "submitting to Apple for notarisation (a few minutes)..."
    # One-time setup of the profile this reads:
    #   xcrun notarytool store-credentials qcportal --apple-id <you@example.com> \
    #     --team-id <TEAMID> --password <app-specific-password>
    xcrun notarytool submit "$DMG" --keychain-profile "$NOTARY_PROFILE" --wait
    # Stapling is what lets a machine with no network still see the ticket.
    xcrun stapler staple "$DMG"
    xcrun stapler validate "$DMG" && echo "notarised and stapled - a downloaded copy will double-click"
  else
    echo "signed but NOT notarised (set QC_NOTARY_PROFILE) - a browser download will still be blocked"
  fi
fi

printf 'built %s (%s)\n' "$DMG" "$(du -h "$DMG" | cut -f1)"
