#!/usr/bin/env bash
# Create ~/Applications/QC Portal.app — a launcher bundle, so the portal starts from
# Launchpad/Spotlight instead of a terminal, in its own window rather than a tab. Called at the end of the root install.sh
# on macOS only; safe to run again on its own.
#
#   bash installer/macos/shortcut.sh [install-dir]
#
# It is a LAUNCHER, not the app: three files that exec the same
# bin/qc-portal.mjs the `qc-portal` command runs. It never clones, installs or
# builds — that is install.sh's job, and a second implementation of it would drift.
set -euo pipefail

INSTALL_DIR="${1:-${QC_PORTAL_HOME:-$HOME/.qc-portal}}"
APP="$HOME/Applications/QC Portal.app"
ENTRY="$INSTALL_DIR/bin/qc-portal.mjs"
ICNS="$INSTALL_DIR/installer/icons/qc-portal.icns"

[ "$(uname -s)" = 'Darwin' ] || { printf '  not macOS — skipping the app bundle.\n'; exit 0; }
[ -f "$ENTRY" ] || { printf '  no install at %s — skipping the app bundle.\n' "$INSTALL_DIR"; exit 0; }

NODE_BIN="$(command -v node || true)"
[ -n "$NODE_BIN" ] || { printf '  node not found — skipping the app bundle.\n'; exit 0; }

VERSION="$(node -e "process.stdout.write(require('$INSTALL_DIR/package.json').version)" 2>/dev/null || echo 0)"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>QC Portal</string>
  <key>CFBundleDisplayName</key><string>QC Portal</string>
  <key>CFBundleIdentifier</key><string>com.stsdata.qcportal.launcher</string>
  <key>CFBundleVersion</key><string>$VERSION</string>
  <key>CFBundleShortVersionString</key><string>$VERSION</string>
  <key>CFBundleExecutable</key><string>qc-portal</string>
  <key>CFBundleIconFile</key><string>qc-portal</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <!-- The launcher starts the server, opens the browser and exits. Without this the
       bundle would sit in the Dock as a running app that owns no window. -->
  <key>LSUIElement</key><true/>
</dict>
</plist>
PLIST
[ -f "$ICNS" ] && cp "$ICNS" "$APP/Contents/Resources/qc-portal.icns"
cat > "$APP/Contents/MacOS/qc-portal" <<LAUNCH
#!/bin/bash
# Generated by installer/macos/shortcut.sh.
#
# --app is what makes this feel like a desktop app: the launcher starts the server
# and then shows it in a chromeless Chromium window (no tabs, no address bar)
# instead of a browser tab. See openAppWindow() in bin/qc-portal.mjs.
#
# A GUI launch has almost no PATH, so node is addressed absolutely, not looked up.
exec "$NODE_BIN" "$ENTRY" --app
LAUNCH
chmod +x "$APP/Contents/MacOS/qc-portal"
touch "$APP"   # nudge Finder/Dock off a cached generic icon
printf '  app: %s\n' "$APP"
